// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SS.Alteration.Persistence.Contexts;

#nullable disable

namespace SS.Alteration.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221002121127_mig_1")]
    partial class mig_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SuitId");

                    b.ToTable("AlterationForms");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlterationFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlterationFormId");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlterationFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlterationFormId");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffe9e797-5f48-4ee7-bf53-3b74f3cc64c7"),
                            CreatedAt = new DateTime(2022, 10, 2, 12, 11, 27, 243, DateTimeKind.Utc).AddTicks(4347),
                            Name = "Received"
                        },
                        new
                        {
                            Id = new Guid("961aefcd-b680-44ed-9f96-ba68201c3274"),
                            CreatedAt = new DateTime(2022, 10, 2, 12, 11, 27, 243, DateTimeKind.Utc).AddTicks(4371),
                            Name = "InProgress"
                        },
                        new
                        {
                            Id = new Guid("8a98b5b0-0710-49e4-bbb4-f38ff9506fb1"),
                            CreatedAt = new DateTime(2022, 10, 2, 12, 11, 27, 243, DateTimeKind.Utc).AddTicks(4373),
                            Name = "Ready"
                        });
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Suit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Suits");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.HasOne("SS.Alteration.Domain.Entities.Suit", "Suit")
                        .WithMany()
                        .HasForeignKey("SuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suit");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Instruction", b =>
                {
                    b.HasOne("SS.Alteration.Domain.Entities.AlterationForm", "AlterationForm")
                        .WithMany("Instructions")
                        .HasForeignKey("AlterationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlterationForm");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Order", b =>
                {
                    b.HasOne("SS.Alteration.Domain.Entities.AlterationForm", "AlterationForm")
                        .WithMany()
                        .HasForeignKey("AlterationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SS.Alteration.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlterationForm");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
