// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SS.Alteration.Persistence.Contexts;

#nullable disable

namespace SS.Alteration.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221001231933_mig_2")]
    partial class mig_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlterationStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<Guid>("SuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlterationStatusId");

                    b.ToTable("AlterationForms");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AlterationStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b33f452-fb57-4d1b-97d9-472bc11fc8cb"),
                            CreatedAt = new DateTime(2022, 10, 1, 23, 19, 33, 561, DateTimeKind.Utc).AddTicks(8723),
                            Name = "Received",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("419a5cfd-73e6-4830-9a3d-beeec6a23fe0"),
                            CreatedAt = new DateTime(2022, 10, 1, 23, 19, 33, 561, DateTimeKind.Utc).AddTicks(8823),
                            Name = "InProgress",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("db493fba-2f22-4948-b000-9989d4f31846"),
                            CreatedAt = new DateTime(2022, 10, 1, 23, 19, 33, 561, DateTimeKind.Utc).AddTicks(8825),
                            Name = "Ready",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlterationFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlterationFormId");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.HasOne("SS.Alteration.Domain.Entities.AlterationStatus", "AlterationStatus")
                        .WithMany("AlterationForms")
                        .HasForeignKey("AlterationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlterationStatus");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Instruction", b =>
                {
                    b.HasOne("SS.Alteration.Domain.Entities.AlterationForm", "AlterationForm")
                        .WithMany("Instructions")
                        .HasForeignKey("AlterationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlterationForm");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationStatus", b =>
                {
                    b.Navigation("AlterationForms");
                });
#pragma warning restore 612, 618
        }
    }
}
