// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SS.Alteration.Persistence.Contexts;

#nullable disable

namespace SS.Alteration.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221001232042_mig_3")]
    partial class mig_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlterationStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<Guid>("SuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlterationStatusId");

                    b.ToTable("AlterationForms");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AlterationStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff0120fa-5a63-4b36-8388-e6f89f11e949"),
                            CreatedAt = new DateTime(2022, 10, 1, 23, 20, 42, 665, DateTimeKind.Utc).AddTicks(3950),
                            Name = "Received"
                        },
                        new
                        {
                            Id = new Guid("984344a6-4fcb-4be5-ab53-ab120244ea5f"),
                            CreatedAt = new DateTime(2022, 10, 1, 23, 20, 42, 665, DateTimeKind.Utc).AddTicks(3978),
                            Name = "InProgress"
                        },
                        new
                        {
                            Id = new Guid("aa22709b-77c9-434a-8ac1-128e76cef7b0"),
                            CreatedAt = new DateTime(2022, 10, 1, 23, 20, 42, 665, DateTimeKind.Utc).AddTicks(3980),
                            Name = "Ready"
                        });
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlterationFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlterationFormId");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.HasOne("SS.Alteration.Domain.Entities.AlterationStatus", "AlterationStatus")
                        .WithMany("AlterationForms")
                        .HasForeignKey("AlterationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlterationStatus");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Instruction", b =>
                {
                    b.HasOne("SS.Alteration.Domain.Entities.AlterationForm", "AlterationForm")
                        .WithMany("Instructions")
                        .HasForeignKey("AlterationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlterationForm");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationStatus", b =>
                {
                    b.Navigation("AlterationForms");
                });
#pragma warning restore 612, 618
        }
    }
}
