// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SS.Alteration.Persistence.Contexts;

#nullable disable

namespace SS.Alteration.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlterationStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<Guid>("SuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlterationStatusId");

                    b.ToTable("AlterationForms");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AlterationStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fdcb36c8-b345-4984-a25e-616154ec3610"),
                            CreatedAt = new DateTime(2022, 10, 2, 9, 26, 4, 626, DateTimeKind.Utc).AddTicks(2846),
                            Name = "Received"
                        },
                        new
                        {
                            Id = new Guid("a155c0ae-f226-41e1-8282-d9012558e1ff"),
                            CreatedAt = new DateTime(2022, 10, 2, 9, 26, 4, 626, DateTimeKind.Utc).AddTicks(2871),
                            Name = "InProgress"
                        },
                        new
                        {
                            Id = new Guid("42f20caa-d8c0-4a50-9f8e-d89b81b3ad4f"),
                            CreatedAt = new DateTime(2022, 10, 2, 9, 26, 4, 626, DateTimeKind.Utc).AddTicks(2873),
                            Name = "Ready"
                        });
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlterationFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlterationFormId");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.HasOne("SS.Alteration.Domain.Entities.AlterationStatus", "AlterationStatus")
                        .WithMany("AlterationForms")
                        .HasForeignKey("AlterationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlterationStatus");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.Instruction", b =>
                {
                    b.HasOne("SS.Alteration.Domain.Entities.AlterationForm", "AlterationForm")
                        .WithMany("Instructions")
                        .HasForeignKey("AlterationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlterationForm");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationForm", b =>
                {
                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("SS.Alteration.Domain.Entities.AlterationStatus", b =>
                {
                    b.Navigation("AlterationForms");
                });
#pragma warning restore 612, 618
        }
    }
}
